# Generated by Django 4.0.3 on 2022-03-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='film',
            name='slang',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
