# Generated by Django 4.0.3 on 2022-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0002_alter_film_photo_alter_film_slang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='content',
            field=models.TextField(verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='date_publisher',
            field=models.DateField(verbose_name='Дата выхода фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='en_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='films_gallery.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='is_published',
            field=models.BooleanField(verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг фильма (0, 100)'),
        ),
        migrations.AlterField(
            model_name='film',
            name='slang',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='time',
            field=models.IntegerField(verbose_name='Длительность фильма'),
        ),
    ]
