# Generated by Django 4.0.3 on 2022-03-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0005_producer_alter_film_title_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='genre',
            field=models.ManyToManyField(to='films_gallery.genre', verbose_name='Жанры'),
        ),
    ]
