# Generated by Django 4.0.3 on 2022-03-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0006_producer_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
