# Generated by Django 4.0.3 on 2022-03-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0007_producer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Имя'),
        ),
    ]
