# Generated by Django 4.0.3 on 2022-03-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0009_alter_producer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Место рождения'),
        ),
    ]
