# Generated by Django 4.0.3 on 2022-03-31 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0010_alter_producer_place_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанры', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['name'], 'verbose_name': 'Режиссеры', 'verbose_name_plural': 'Режиссеры'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_gallery.film')),
            ],
        ),
    ]
