# Generated by Django 4.0.3 on 2022-03-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0011_alter_genre_options_alter_producer_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['film'], 'verbose_name': 'Коментарии', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
