# Generated by Django 4.0.3 on 2022-03-31 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0012_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films_gallery.comment'),
        ),
    ]
