# Generated by Django 4.0.3 on 2022-03-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0013_remove_comment_film_film_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='comment',
        ),
        migrations.AddField(
            model_name='film',
            name='comment',
            field=models.ManyToManyField(null=True, to='films_gallery.comment'),
        ),
    ]
