# Generated by Django 4.0.3 on 2022-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0015_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
