# Generated by Django 4.0.3 on 2022-03-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_gallery', '0016_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='comment',
            field=models.ManyToManyField(to='films_gallery.comment'),
        ),
    ]
